Xqsf 2 create works page
wood-block/web pull request #11
Opened 2022-10-04 14:56 UTC by SatelliteSilver

XQSF-2-create-works-page -> develop

2022-10-04 15:02 UTC, SatelliteSilver commented
.main_block 에 아래 옵션 필요할 듯
min-height: 100vh;
height: 100%;

2022-10-04 15:13 UTC, yoonlight requested changes

2022-10-04 15:13 UTC, yoonlight commented on css/works.css
> +section {
class 명 추가 및 section -> .class 이름 형태로 변경

2022-10-04 15:13 UTC, yoonlight commented on works.html
> +            <section>
class 명 추가

2022-10-04 15:13 UTC, yoonlight commented on css/works.css
> +    display: none;
- class name 오타
- display: none 왜?
- min-height: 100vh 추가
- height: 100% 추가

2022-10-04 15:23 UTC, SatelliteSilver commented on css/works.css
> +    display: none;
display: none 엥 이게 왜 들어갔지,, 언제부터 들어간거지,, 뭔가 테스트하다가 안뺐나봄
삭제하였습니다

2022-10-05 01:59 UTC, yoonlight approved these changes

2022-10-05 01:59 UTC, merged